### PR TITLE
Fix UndefVarError when unsubscribing 

### LINKED ISSUE #78: Unsubscribe gives an UndefVarError
Unsubscribing from a channel leads to an ERROR: UndefVarError: unshift! not defined.

```
subscribe(sub, "NewTask", print)
unsubscribe(sub, "NewTask")

**ERROR: UndefVarError: unshift! not defined**
**Stacktrace:
 [1] unsubscribe(::SubscriptionConnection, ::String) at C:\Users\markusb\.julia\packages\Redis\KsyS4\src\commands.jl:307
 [2] top-level scope at REPL[5]:1**
```

This comes from here:
https://github.com/JuliaDatabases/Redis.jl/blob/d0f4bb972db907aab60694377d335c04f0c650a4/src/commands.jl#L307

unshift! was renamed to pushfirst!, see https://stackoverflow.com/questions/63490410/julia-undefvarerror-unshift-not-defined

### PR DESCRIPTION
**Pull request by mbrachner**
Fixes #78 and adds a unsubscribe test into pub/sub testset.

### CODE REVIEW

**Comment by jkaye2012** [comment]
Hey there,

I see this is still a draft; once it's ready to go, I'd be happy to merge this.

**Comment by mbrachner** [comment]
Sorry, somehow I have missed this. Putting it on ready for review.

**Comment by david-macmahon** [comment]
For anyone else looking for the solution to the "unshift! not defined" error when unsubscribing, it looks like this PR has been superseded by the already merged PR #81.  This PR should probably be closed.

**Comment by jkaye2012** [comment]
This has been resolved by #81

**Pull request closed without merging**
