### PR TITLE
Fix union nothing returns

### PR DESCRIPTION
**Pull request by vitornesello**
This is a proposal to fix issue #88

### CODE REVIEW

**Comment by jkaye2012** [comment]
Thanks for the PR. I'm going to try to get CI set back up this weekend, then will run it against this PR and hopefully look at the few other outstanding issues that we have right now.

**Comment by vitornesello** [comment]
I ran the tests in the master version locally and some of them failed. I am not sure why..

If you could tell me how/where to implement the tests for the case that this MR is supposed to fix, I would be happy to do so!

**Comment by vitornesello** [comment]
Hi @jkaye2012 !

Any news for this PR?

**Comment by jkaye2012** [comment]
To be honest, it had completely slipped my mind. I'll take a look this Sunday!

**Comment by vitornesello** [comment]
@jkaye2012 ping 😆

**Pull request merged**
